[build]
builder = "nixpacks"
buildCommand = "npm run build"

[deploy]
startCommand = "npx serve dist -s -l 3000"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[nixpacks]
providers = ["node"]

